
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `CRM_HOPPOSITIONHOTPOSITION`
-- ----------------------------
DROP TABLE IF EXISTS `CRM_HOPPOSITIONHOTPOSITION`;
CREATE TABLE `CRM_HOPPOSITIONHOTPOSITION` (
 		`HOTPOSITION_ID` varchar(100) NOT NULL,
		`HOTNAME` varchar(255) DEFAULT NULL COMMENT '热门职位',
  		PRIMARY KEY (`HOTPOSITION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
