GO
/****** FHQQ313596790 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE CRM_MEMBER (
 		MEMBER_ID  nvarchar(100) NOT NULL,
		MEMBER_NUM nvarchar(20) DEFAULT NULL,
		ENTERPRISE_NAME nvarchar(100) DEFAULT NULL,
		CONTACT_PHONE nvarchar(20) DEFAULT NULL,
		ENTERPRISE_ADDRESS nvarchar(100) DEFAULT NULL,
		RECRUIT_CNT int NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MEMBER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
