GO
/****** FHQQ313596790 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE CRM_HOPPOSITIONHOTPOSITION (
 		HOTPOSITION_ID  nvarchar(100) NOT NULL,
		HOTNAME nvarchar(255) DEFAULT NULL,
PRIMARY KEY CLUSTERED 
(
	[HOTPOSITION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
